# Generated by Django 3.2.16 on 2022-10-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsboard', '0008_alter_new_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='newsboard.category', verbose_name='category'),
        ),
    ]
